version: 0.2
phases:
    install:
        commands:
          - yum update
          - yum install docker
          - service docker start
          - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
          - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - aws --version
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 730335196817.dkr.ecr.us-east-1.amazonaws.com
            - REPOSITORY_URI=730335196817.dkr.ecr.us-east-1.amazonaws.com/rubin-portfolio
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - IMAGE_TAG=${COMMIT_HASH:=latest}
            - CLUSTER_NAME=blazorserverapp
            - SERVICE_NAME=blazorserverapp
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker image...          
            - docker build -t $REPOSITORY_URI:latest .
            - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker images...
            - docker push $REPOSITORY_URI:latest
            - docker push $REPOSITORY_URI:$IMAGE_TAG
            - echo Writing image definitions file...
            - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment --region us-east-1